project:
  type: website
  render:
    - index.qmd
    - about.qmd
    - quarto_tutorial/hello.ipynb
    - roessler_tutorial/test_polar_roessler.ipynb
    - networks_tutorial/network_perturbations.ipynb

website:
  title: "Cerebral Dynamics"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    toc: true
